#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later

from os import environ, scandir
from sys import argv, stderr

def print_no_lf(*args):
	print(*args, end = '')

def sort_deps(item):
	return not isinstance(item, list)

def find_deps(dir):
	ents = scandir(dir)
	deps = [ dir ]

	for ent in ents:
		item = ent.path

		if item.endswith('_entry.c'):
			continue

		if not '.' in ent.name:
			item = find_deps(ent.path)

		deps.append(item)

	return deps

def print_headers(deps):
	first = 1

	for item in deps:
		if isinstance(item, list):
			print_headers(item)
			continue

		if first:
			print_no_lf(f"include/{item}/d.h: |")
		else:
			print_no_lf(f" {item}")

		first = 0

	print('\n')

def print_object_deps(deps):
	first = 1

	for item in deps:
		if isinstance(item, list):
			print_object_deps(item)
			continue

		if first:
			header = item

			print_no_lf(f"$(objtree)/{item}.o")
		else:
			print_no_lf(f" $(objtree)/{item[0:-2]}.o")

		first = 0

	print(f": include/{header}/d.h\n")

def print_rules(deps):
	first = 1
	sub = []

	for item in deps:
		if isinstance(item, list):
			print_rules(item)
			sub.append(item[0])
			continue

		if first:
			print_no_lf(f"$(objtree)/{item}/entry:")
			print_no_lf(f" $(objtree)/{item}.o")
			print_no_lf(f" $(objtree)/{item}_entry.o")
		else:
			print_no_lf(f" $(objtree)/{item[0:-2]}.o")

		first = 0

	for item in sub:
		print_no_lf(f" $(objtree)/{item}/entry")

	print('\n')

main = argv[1]
init = main.split('.')[0]
deps = find_deps(init)

deps.sort(key = sort_deps)

print(f"# Generated by {argv[0]}\n")

print_headers(deps)

print_object_deps(deps)

print_rules(deps)
