#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

trap 'rm -f .tmp-$$' EXIT

p=$1
pu=$(printf '%s' $1 | tr [:lower:] [:upper:])
match='s|.*/\([^/]*\).c'

cat >.tmp-$$

cat <<EOF
/* Generated by $0 */

#ifndef CMD_${pu}_D_H
#define CMD_${pu}_D_H

#include "parse_argv.h"

EOF

cat .tmp-$$ | \
sed $match"|int cmd_${p}_\1(int argc, const char **argv);|"

printf '\n'

cat .tmp-$$ | \
sed $match"|extern const char *cmd_${p}_\1_help;|"

printf '\n'

cat <<EOF
#define CMD_${pu}_CMDS \\
EOF

sed '$d' .tmp-$$ | \
sed $match"|\tPA_OPT_CMD(\"\1\", cmd_${p}_\1, cmd_${p}_\1_help), \\\\|"

tail -n1 .tmp-$$ | \
sed $match"|\tPA_OPT_CMD(\"\1\", cmd_${p}_\1, cmd_${p}_\1_help),|"

cat <<EOF

#endif /* CMD_${pu}_D_H */
EOF
